### ISSUE TITLE
Hello Word in PHP  😲 

### ISSUE THREAD

**Issue by mariobeltran99** [AlexanderSiguenza/PrimerProyectoGitPHP#1]
Un hola mundo solo en un repositorio es mala práctica Ingeniero xD jajaja

**Comment by AlexanderSiguenza** [comment]
jajajajaj creo que GitHub me va demandar por profanar este espacio. Para fines ilustrativos, estoy dando la materia de php y no sabían manejar git y esta es la manera mas simple de iniciar. Prometo borrarlo pronto jajajaja

**Comment by mariobeltran99** [comment]
Jajaja que genial, hubiera preferido que usted me diera esa materia de PHP, jajaj no hay problema si es con fines esta correcto, se la valgo xd jajajaja.
